# Generated by Django 3.2.12 on 2023-08-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230809_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
